name: Docker Multi-arch Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and load amd64 for testing
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/Dockerfile.minimal
          platforms: linux/amd64
          load: true
          tags: myapp:amd64
      
      - name: Build and load arm64 for testing
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/Dockerfile.minimal
          platforms: linux/arm64
          load: true
          tags: myapp:arm64
      
      - name: Test amd64 container
        run: docker run --rm myapp:amd64 python -m xtts_api_server
      
      - name: Test arm64 container
        run: docker run --rm --platform linux/arm64 myapp:arm64 python -m xtts_api_server
      
      - name: Build final multi-arch images
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/Dockerfile.minimal
          platforms: linux/amd64,linux/arm64
          outputs: type=docker,dest=images.tar
          tags: myapp:latest
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: images.tar
